name: CI/CD on AWS

on:
  push:
    branches:
      - main

env: 
  AWS_REGION: ap-south-1
  EKS_CLUSTER_NAME: pc-eks
  HELM_CHART_NAME: nginx

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials  
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update KubeConfig 
      run: |   
         aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region=${{ env.AWS_REGION }}
      
    - name: Check Helm Release Existence
      id: helm_check
      run: |
        if helm status ${{ env.HELM_CHART_NAME }} >/dev/null 2>&1; then
          echo "Helm release ${{ env.HELM_CHART_NAME }} exists."
          echo "::set-output name=exists::true"
        else
          echo "Helm release ${{ env.HELM_CHART_NAME }} does not exist."
          echo "::set-output name=exists::false"
        fi

    - name: Deploy Helm Chart To Amazon EKS Cluster 
      if: steps.helm_check.outputs.exists == 'false'
      run: |
         helm install ${{ env.HELM_CHART_NAME }} nginx-helm-chart/
      else
      run: |
         helm upgrade ${{ env.HELM_CHART_NAME }} nginx-helm-chart/
